webapp/tours/urls.py
from django.conf.urls import url

from .views import (
    employee,
    employee_tour_create,
    employee_tour_details,
    employee_tour_draft_submit,
    employee_tour_edit,
    employee_tour_list,
    employee_tour_list_status,
    finance_manager,
    finance_manager_list,
    finance_manager_list_status,
    finance_manager_tour_details,
    finance_manager_tour_details_edit,
    manager,
    manager_list,
    manager_list_status,
    manager_tour_details,
    manager_tour_details_edit,
    manager_tour_details_submit,
    route,

)
urlpatterns = [
    url(r'^$', route, name='route'),
    url(r'^employee/(?P<account_id>\d+)/$', employee, name='emp'),
    url(r'^employee/(?P<account_id>\d+)/(?P<tour_id>\d+)/$', employee_tour_details, name='emp-detail'),
    url(r'^employee/(?P<account_id>\d+)/(?P<tour_id>\d+)/edit/$', employee_tour_edit, name='emp-detail-edit'),
    url(r'^employee/(?P<account_id>\d+)/create/$', employee_tour_create, name='emp-create'),
    url(r'^employee/(?P<account_id>\d+)/list/$', employee_tour_list, name='emp-list'),
    url(r'^employee/(?P<account_id>\d+)/list/(?P<status>[\w\-]+)/$', employee_tour_list_status, name='emp-list-status'),
    url(r'^employee/(?P<account_id>\d+)/(?P<tour_id>\d+)/draft/submit/$', employee_tour_draft_submit, name='emp-draft-submit'),

    url(r'^manager/(?P<account_id>\d+)/$', manager, name='man'),
    url(r'^manager/(?P<account_id>\d+)/emp-tour-list/$', manager_list, name='man-list'),
    url(r'^manager/(?P<account_id>\d+)/emp-tour-list/(?P<status>[\w\-]+)/$', manager_list_status, name='man-list-status'),
    url(
        r'^manager/(?P<account_id>\d+)/emp-tour-detail/(?P<tour_id>\d+)/(?P<status>[\w\-]+)/$', 
        manager_tour_details, 
        name='man-tour-details'
    ),
    url(
        r'^manager/(?P<account_id>\d+)/emp-tour-detail/(?P<tour_id>\d+)/pending/change-to/(?P<status>[\w\-]+)/$', 
        manager_tour_details_edit, 
        name='man-tour-details-edit'
    ),
    url(
        r'^manager/(?P<account_id>\d+)/emp-tour-detail/(?P<tour_id>\d+)/approved/submit/$', 
        manager_tour_details_submit, 
        name='man-tour-details-submit'
    ),

    url(r'^finance-manager/(?P<account_id>\d+)/$', finance_manager, name='fin-man'),
    url(r'^finance-manager/(?P<account_id>\d+)/emp-tour-list/$', finance_manager_list, name='fin-man-list'),
    url(r'^finance-manager/(?P<account_id>\d+)/emp-tour-list/(?P<status>[\w\-]+)/$', finance_manager_list_status, name='fin-man-list-status'),
    url(
        r'^finance-manager/(?P<account_id>\d+)/emp-tour-detail/(?P<tour_id>\d+)/(?P<status>[\w\-]+)/$', 
        finance_manager_tour_details, 
        name='fin-man-tour-details'
    ),
    url(
        r'^finance-manager/(?P<account_id>\d+)/emp-tour-detail/(?P<tour_id>\d+)/pending/change-to/(?P<status>[\w\-]+)/$', 
        finance_manager_tour_details_edit, 
        name='fin-man-tour-details-edit'
    ),
]

webapp/webapp/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.contrib import admin
from django.contrib.auth.views import login
from django.conf.urls.static import static

from tours import views as tour_views

urlpatterns = [
    url(r'^$', tour_views.route, name='tour_route'),
    url(r'^accounts/login/$', login),
    url(r'^admin/', admin.site.urls),
    url(r'^logout/$', tour_views.logout_page, name='logout'),
    url(r'^tour/', include('tours.urls', namespace='tour')),
] 

if settings.DEBUG is True:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

webapp/tours/forms.py
import floppyforms.__future__ as forms
#from django import forms


from pagedown.widgets import PagedownWidget

from .models import EmployeeTourRequest

class EmployeeTourRequestForm(forms.ModelForm):
    purpose = forms.CharField(widget=PagedownWidget(show_preview=False))

    class Meta:
        model = EmployeeTourRequest
        fields = [
            'tour_name',
            'purpose',
            'start_date',
            'end_date',
            'mode_of_travel',
            'ticket_cost',
            'hotel_cost',
            'airport_cab_cost_home',
            'airport_cab_cost_dest',
            'bills_image',
            'bills_image_caption',
            'approving_manager',
            'local_conveyance',
            'draft',
        ]

    def clean(self):
        cleaned_data = super(EmployeeTourRequestForm, self).clean()
        start_date = cleaned_data.get("start_date")
        end_date = cleaned_data.get("end_date")

        if end_date < start_date:
            msg = u"End date should be greater than or equal to start date."
            self._errors["end_date"] = self.error_class([msg])

webapp/tours/views.py
from django.contrib import messages
from django.contrib.auth import logout
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect, Http404
from django.db.models import Count
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse

from employee_accounts.models import EmployeeAccount
from .forms import EmployeeTourRequestForm 
from .models import EmployeeRequestStatus, EmployeeTourRequest, EmployeeTourRequestStatus  

REDIRECT_ACCOUNT = {
    1: 'tour:emp',
    2: 'tour:man',
    3: 'tour:fin-man',

}

REQUEST_STATUS = {
    'pending': {
        'id': 1,
        'status': 'Pending'
    },
    'approved': { 
        'id': 2,
        'status': 'Approved'
    },
    'rejected': { 
        'id': 3,
        'status': 'Rejected'
    },
    'request-for-info': {
        'id': 4,
        'status': 'Request For Information'
    },
    'draft': {
        'id': 5,
        'status': 'Draft'
    },
}

#Utility Functions
def get_employee_account_or_redirect_to_admin(**kwargs):
    try:
        e = EmployeeAccount.objects.get(**kwargs)
    except EmployeeAccount.DoesNotExist:
        return redirect('/admin/')
    return e

def account_position_page_validate_or_redirect(account_id, expected_account_id):
    ea = get_employee_account_or_redirect_to_admin(pk=account_id)
    if ea.account_position.id != expected_account_id:
        return redirect(REDIRECT_ACCOUNT[ea.account_position.pk], account_id=ea.pk)
    return ea

def paginate_list(list_obj, page_req_var):
    paginator = Paginator(list_obj, 10)
    try:
        pl = paginator.page(page_req_var)
    except PageNotAnInteger:
        pl = paginator.page(1)
    except EmptyPage:
        pl = paginator.page(paginator.num_pages)
    return pl


#View Functions
@login_required
def route(request):
    if request.user.is_superuser:
        return redirect('/admin/')

    ea = get_employee_account_or_redirect_to_admin(account=request.user)
    return redirect(REDIRECT_ACCOUNT[ea.account_position.pk], account_id=ea.pk)

#---EMPLOYEE VIEWS---#
@login_required
def employee(request, account_id):
    ea = account_position_page_validate_or_redirect(account_id, 1)
    et = EmployeeTourRequest.objects.filter(employee=ea)
    etr = et.values('request_status').annotate(total=Count('request_status'))
    
    tour_list = paginate_list(et.order_by('-date_modified'), request.GET.get('page'))
    context = {
            'user': ea.account.username,
            'employee_account': ea, 
            'emp_tours': tour_list,
            'pending_count': next((item for item in etr if item["request_status"] == 1), {'request_status': 1, 'total': 0})['total'],
            'approved_count': next((item for item in etr if item["request_status"] == 2), {'request_status': 2, 'total': 0})['total'],
            'rejected_count': next((item for item in etr if item["request_status"] == 3), {'request_status': 3, 'total': 0})['total'],
            'rfi_count': next((item for item in etr if item["request_status"] == 4), {'request_status': 4, 'total': 0})['total'],
            'tour_id': ea.pk,
        }

    return render(request, "tours/employee_dashboard.html", context)

@login_required
def employee_tour_create(request, account_id):
    ea = account_position_page_validate_or_redirect(account_id, 1)

    form = EmployeeTourRequestForm(request.POST or None, request.FILES or None)
    if form.is_valid():
            instance = form.save(commit=False)
            instance.employee = ea
            if not instance.draft:
                pending_obj = EmployeeRequestStatus.objects.get(status_name='Pending')
                instance.request_status = pending_obj
            instance.save()
            # message success
            messages.success(request, "Successfully Created!")
            return redirect('tour:emp-detail', account_id=ea.pk, tour_id=instance.pk)
    context = {
            'user': ea.account.username,
            'form': form,
            'tour_id': ea.pk,
    }

    return render(request, "tours/employee_tour_create.html", context)

@login_required
def employee_tour_edit(request, account_id, tour_id):
    ea = account_position_page_validate_or_redirect(account_id, 1)
    emp_tour = get_object_or_404(EmployeeTourRequest, employee=ea, pk=tour_id)

    form = EmployeeTourRequestForm(request.POST or None, request.FILES or None, instance=emp_tour)
    if form.is_valid():
            instance = form.save(commit=False)
            instance.employee = ea
            instance.save()
            # message success
            messages.success(request, "Successfully Updated!")
            return redirect('tour:emp-detail', account_id=ea.pk, tour_id=instance.pk)
    context = {
            'user': ea.account.username,
            "form": form,
    }

    return render(request, "tours/employee_tour_create.html", context)

@login_required
def employee_tour_list(request, account_id):
    ea = account_position_page_validate_or_redirect(account_id, 1)
    etr = EmployeeTourRequest.objects.filter(employee=ea)
    tour_list = paginate_list(etr.order_by('-date_modified'), request.GET.get('page'))
    etr_req = etr.values('request_status').annotate(total=Count('request_status'))
    etr_draft = etr.values('draft').annotate(total=Count('draft'))

    context = {
            'employee_account': ea, 
            'user': ea.account.username,
            'tours': tour_list,
            'tour_id': ea.pk,
	    'tour_count': etr.count(),
            'pending_count': next((item for item in etr_req if item["request_status"] == 1), {'request_status': 1, 'total': 0})['total'],
            'approved_count': next((item for item in etr_req if item["request_status"] == 2), {'request_status': 2, 'total': 0})['total'],
            'rejected_count': next((item for item in etr_req if item["request_status"] == 3), {'request_status': 3, 'total': 0})['total'],
            'rfi_count': next((item for item in etr_req if item["request_status"] == 4), {'request_status': 4, 'total': 0})['total'],
            'draft_count': next((item for item in etr_draft if item["draft"] == True), {'draft': True, 'total': 0})['total']	
        }

    return render(request, "tours/employee_tour_list.html", context)

def employee_tour_list_status(request, account_id, status):
    ea = account_position_page_validate_or_redirect(account_id, 1)
    status_id = None
    etr = None
    if status == 'draft':
        etr = EmployeeTourRequest.objects.filter(
                    employee=ea,
                    draft=True,
                )
        status_id = 5
    else:
        if status in REQUEST_STATUS:
            status_id = REQUEST_STATUS[status]['id']
        else:
            return render(request, "404.html", {})

        etr = EmployeeTourRequest.objects.filter(
                    employee=ea,
                    request_status__pk=status_id,
                )

    tour_list = paginate_list(etr.order_by('-date_modified'), request.GET.get('page'))
    context = {
            'employee_account': ea, 
            'user': ea.account.username,
            'tours': tour_list,
            'tour_id': ea.pk,
            'status': REQUEST_STATUS[status]['status'],
            'status_id': status_id,
            'status_link': status,
            'account_id': account_id,
        }

    return render(request, "tours/employee_tour_list_status.html", context)

@login_required
def employee_tour_details(request, account_id, tour_id):
    ea = account_position_page_validate_or_redirect(account_id, 1)
    etr = get_object_or_404(EmployeeTourRequest, pk=tour_id)

    context = {
            'user': ea.account.username,
            'tour_details': etr,
            'tour_id': ea.pk
        }

    return render(request, "tours/employee_tour_details.html", context)

def employee_tour_draft_submit(request, account_id, tour_id):
    ea = account_position_page_validate_or_redirect(account_id, 1)
    etr = get_object_or_404(EmployeeTourRequest, pk=tour_id, employee=ea)
    status_obj = EmployeeRequestStatus.objects.get(status_name='Pending')
    etr.draft = False
    etr.request_status = status_obj
    etr.save()

    return redirect('tour:emp-list-status', account_id=ea.pk, status='draft')

#---MANAGER VIEWS---#
def manager(request, account_id):
    ea = account_position_page_validate_or_redirect(account_id, 2)
    et = EmployeeTourRequest.objects.filter(approving_manager=ea, draft=False)
    etr = EmployeeTourRequestStatus.objects.filter(emp_tour_req__approving_manager=ea)
    etr_req = etr.values('approved_by_manager').annotate(total=Count('approved_by_manager'))
    x = etr.values('approved_by_manager', 'submitted_to_finance_manager').annotate(total=Count('approved_by_manager'))

    context = {
            'user': ea.account.username,
            'account_id': ea.pk,
            'employee_account': ea, 
            'tours': et,
            'tour_id': ea.pk,
            'pending_count': next(
                    (item for item in etr_req if item["approved_by_manager"] == 1), 
                    {'approved_by_manager': 1, 'total': 0}
                )['total'],
            'for_submission_count': next(
                        (item for item in x if item["approved_by_manager"] == 2 and not item["submitted_to_finance_manager"] ), 
                        {'approved_by_manager': 2, 'total': 0}
                    )['total'],
        }

    return render(request, "tours/manager_dashboard.html", context)

def manager_list(request, account_id):
    ea = account_position_page_validate_or_redirect(account_id, 2)
    etr = EmployeeTourRequestStatus.objects.filter(emp_tour_req__approving_manager=ea)
    tour_list = paginate_list(etr.order_by('-date_modified'), request.GET.get('page'))

    context = {
            'user': ea.account.username,
            'tours': tour_list,
            'account_id': account_id,

webapp/templates/tours/employee_tour_details.html
{% extends "base.html" %}
{% load staticfiles %}

{% block title %}Travel Portal | Employee Tour Detail{% endblock %}
{% block user %}{{ user }}{% endblock %}
{% block sidebar %}
    <li>
        <a href="{% url "tour:route" %}"><i class="fa fa-fw fa-dashboard"></i> Dashboard</a>
    </li>
    <li class='active'>
		{% if finance_manager_user %}
            <a href="{% url "tour:fin-man-list" tour_id %}"><i class="fa fa-fw fa-plane"></i> Tours</a>
		{% elif manager_user %}
            <a href="{% url "tour:man-list" tour_id %}"><i class="fa fa-fw fa-plane"></i> Tours</a>
		{% else %}
            <a href="{% url "tour:emp-list" tour_id %}"><i class="fa fa-fw fa-plane"></i> Tours</a>
        {% endif %}
    </li>
{% endblock %}
{% block content %}
<div id="page-wrapper">
<div class="container-fluid">
    <div class="row">
    <div class="col-lg-12">
        <h1>Tour Details</h1>
        <hr>
        <ol class="breadcrumb">
                <li>
                    <i class="fa fa-dashboard"></i> <a href="{% url "tour:route" %}">Dashboard</a>
                </li>
                <li class="">
                        {% if finance_manager_user %}
                            <a href="{% url "tour:fin-man-list" tour_id %}"><i class="fa fa-fw fa-plane"></i> Tours</a>
                        {% elif manager_user %}
                            <a href="{% url "tour:man-list" tour_id %}"><i class="fa fa-fw fa-plane"></i> Tours</a>
                        {% else %}
                            <a href="{% url "tour:emp-list" tour_id %}"><i class="fa fa-fw fa-plane"></i> Tours</a>
                        {% endif %}
                </li>
                <li class="active">
                        <i class="fa fa-file-text"></i> Details
                </li>

        </ol>
    </div>
    </div>
	<!-- Result -->
	{% if messages %}
		<div class='messages'>
			<ul class="messages alert alert-success">
				{% for message in messages %}
					<li{% if message.tags %} class="{{ message.tags }}"{% endif %}>
						{% if "html_safe" in message.tags %}
								{{ message|safe }}
						{% else %}
							{{ message }}
						{% endif %}
					</li>
				{% endfor %}
			</ul>
		</div>
	{% endif %}
	<div class="row">
	
	{% if status_id == 1 %}
		{% if finance_manager_user %}
			<div class='col-md-6'>
				<table class="table table-bordered">
					<thead>
					<tr>
						<th colspan="2" class="text-center">Manager</th>
						<th>Finance Manager</th>
					</tr>
					</thead>
					<tbody>
					<tr>
						<td>Approved and Submitted By:</td>
						<td>{{ tour_details.approving_manager }}</td>
						<td>
							<form action="{% url 'tour:fin-man-tour-details-edit' finance_manager_id tour_details.pk 'approved' %}" method="post" style="display: inline;">
								{% csrf_token %}
								<input type="hidden" name="status_id" value="" />
								<button type="submit" class="btn btn-success confirm">
									<i class="fa fa-check-square-o"></i>
								</button>
							</form>
							<form action="{% url 'tour:fin-man-tour-details-edit' finance_manager_id tour_details.pk 'rejected' %}" method="post" style="display: inline;">
								{% csrf_token %}
								<input type="hidden" name="status_id" value="" />
								<button type="submit" class="btn btn-danger confirm">
									<i class="fa fa-close"></i>
								</button>
							</form>
							<form action="{% url 'tour:fin-man-tour-details-edit' finance_manager_id tour_details.pk 'request-for-info' %}" method="post" style="display: inline;">
								{% csrf_token %}
								<input type="hidden" name="status_id" value="" />
								<button type="submit" class="btn btn-info confirm">
									<i class="fa fa-info-circle"></i>
								</button>
							</form>
						</td>
					</tr>
					</tbody>
					{% elif manager_user %}
					<div class='col-md-3'>
					<table class="table table-bordered">
					<thead>
					<tr>
						<th>Approving Manager</th>
					</tr>
					</thead>
					<tbody>
					<tr>
						<td>
							<form id='update_status' action="{% url 'tour:man-tour-details-edit' tour_details.approving_manager.pk tour_details.pk 'approved' %}" method="post" style="display: inline;">
								{% csrf_token %}
								<input type="hidden" name="status_id" value="" />
								<button type="submit" class="btn btn-success confirm">
									<i class="fa fa-check-square-o"></i>
								</button>
							</form>
							<form action="{% url 'tour:man-tour-details-edit' tour_details.approving_manager.pk tour_details.pk 'rejected' %}" method="post" style="display: inline;">
								{% csrf_token %}
								<input type="hidden" name="status_id" value="" />
								<button type="submit" class="btn btn-danger confirm">
									<i class="fa fa-close"></i>
								</button>
							</form>
							<form action="{% url 'tour:man-tour-details-edit' tour_details.approving_manager.pk tour_details.pk 'request-for-info' %}" method="post" style="display: inline;">
								{% csrf_token %}
								<input type="hidden" name="status_id" value="" />
								<button type="submit" class="btn btn-info confirm">
									<i class="fa fa-info-circle"></i>
								</button>
							</form>
						</td>
					</tr>
					</tbody>

					{% endif %}
				</table>

			</div>
			</div>
	{% endif %}

    <div class="panel panel-default">
        <div class="panel-heading" style="background-color: #0393a6; padding-bottom: 30px">
            <div class="row">
                <h1>
                    <div class="col-md-11" style="color: #FFF; ">
                   Moving Walls Employee Tour Request
                    {% if tour_details.draft %}
                        (Draft)
                    </div>
                        <div class="col-md-1">
                            <a href="{% url 'tour:emp-detail-edit' tour_details.employee.id tour_details.id %}">
                            <i class="fa fa-edit" style="color: #FFF"></i>
                        </a>
                        </div>
                    {% endif%}
                </h1>
            </div>
        </div>
        <div class="panel-body">
            <p>{{ tour_details.purpose }}</p>
        </div>
		<ul class="list-group">
            <li class="list-group-item">
                <h2>Details</h2>
                <p><strong>Tour Reference ID:</strong> {{ tour_details }}<p>
                <p><strong>Tour Name:</strong> {{ tour_details.tour_name }}<p>
                <p><strong>Full Name:</strong> {{ tour_details.employee.firstname }} {{ tour_details.employee.lastname }}<p>
                <p><strong>Start Date:</strong> {{ tour_details.start_date }}<p>
                <p><strong>End Date:</strong> {{ tour_details.start_date }}</p>
                <p><strong>Mode Of Travel:</strong> {{ tour_details.mode_of_travel }}</p></br>

                <h4><strong>Cost </strong></h4><hr>
                <p><strong>Ticket:</strong> RM{{ tour_details.ticket_cost }}<p>
                <p><strong>Hotel:</strong>RM{{ tour_details.hotel_cost }} <p>
                <p><strong>Airport Cab Return Home:</strong> RM{{ tour_details.airport_cab_cost_home }}</p>
                <p><strong>Airport Cab Destination:</strong> RM{{ tour_details.airport_cab_cost_dest }}</p>
                <p><strong>Local Conveyance at the tour:</strong> {{ tour_details.local_conveyance }}</p>
                <p><strong>Bills Image:</strong></p>
                {% if tour_details.bills_image %}
                    <img id="myImg" src="{{ tour_details.bills_image.url }}" class="img-responsive" width="300" height="200">
                    <p>{{ tour_details.bills_image_caption }}</p>
					<!-- The Modal -->
					<div id="myModal" class="modal">
					
					  <!-- The Close Button -->
					  <span class="close" onclick="document.getElementById('myModal').style.display='none'" style='color: #FFF'>&times;</span>
					
					  <!-- Modal Content (The Image) -->
					  <img class="modal-content" id="img01">
					
					  <!-- Modal Caption (Image Text) -->
					  <div id="caption"></div>
					</div>
                {% else %}
                    <p>N/A</p>
                {% endif %}
                </br>

                <h4><strong>Tour Status</strong></h4><hr>
                <p><strong>Approving Manager:</strong> {{ tour_details.approving_manager }}</p></br>
                {% if tour_details.draft is False %}
                <p><strong>Status:</strong> {{ tour_details.request_status }}</p></br>
                {% endif %}

            </li>
        </ul>
    </div>
    {% if manager_user %}
        {% if status_id == 2 %}
            {% if not etr_stat.submitted_to_finance_manager %}
                <form id='submit' action="{% url 'tour:man-tour-details-submit' tour_details.approving_manager.pk tour_details.pk %}" method="post" style="display: inline;">
                    {% csrf_token %}
                    <input type="hidden" name="status_id" value="" />
                    <button type="submit" class="btn btn-success">
                        <i class="fa fa-check-square-o"> Submit to Finance Manager</i>
                    </button>
                </form>
            {% endif %}
        {% endif %}
    {% endif %}

</div>
</div>
{% endblock %}

webapp/templates/tours/finance_manager_dashboard.html
{% extends "base.html" %}
{% load staticfiles %}

{% block title %}Travel Portal | Manager{% endblock %}
{% block user %}{{ user }}{% endblock %}
{% block sidebar %}
    <li class='active'>
        <a href="{% url "tour:route" %}"><i class="fa fa-fw fa-dashboard"></i> Dashboard</a>
    </li>
    <li>
        <a href="{% url "tour:fin-man-list" tour_id %}"><i class="fa fa-fw fa-plane"></i> Tours</a>
    </li>
{% endblock %}

{% block content %}
<div id="page-wrapper">
<div class='container-fluid'>
    <div class="row">
    <div class="col-lg-12">
        <h1>Dashboard <small>Finance Manager</small></h1>
        <hr>
        <ol class="breadcrumb">
                <li class="active">
					<i class="fa fa-dashboard"></i> Dashboard
                </li>
        </ol>
    </div>
    </div>
	<div class='row'>
		<div class=" col-md-3 col-sm-3">
			<div class="style-box-one Style-one-clr-approve">
                <a href="{% url 'tour:fin-man-list-status' tour_id 'approved' %}">
					<span class="fa fa-check fa-5x"></span>
					 <h5>Approved</h5>
					<i class="fa fa-arrow-circle-right"></i>
				</a>
			</div>
		</div>
		<div class=" col-md-3 col-sm-3">
			<div class="style-box-one Style-one-clr-reject">
                <a href="{% url 'tour:fin-man-list-status' tour_id 'rejected' %}">
					<span class="fa fa-thumbs-down fa-5x"></span>
					 <h5>Rejected</h5>
					<i class="fa fa-arrow-circle-right"></i>
				</a>
			</div>
		</div>
		<div class=" col-md-3 col-sm-3">
			<div class="style-box-one Style-one-clr-pending">
                <a href="{% url 'tour:fin-man-list-status' tour_id 'pending' %}">
					<span class="fa fa-spinner fa-5x"></span>
					 <h5>Pending</h5>
					<i class="fa fa-arrow-circle-right"></i>
				</a>
			</div>
		</div>
		<div class=" col-md-3 col-sm-3">
			<div class="style-box-one Style-one-clr-rfi">
                <a href="{% url 'tour:fin-man-list-status' tour_id 'request-for-info' %}">
					<span class="fa fa-tasks fa-4x"></span>
					 <h5>Request For Information</h5>
					<i class="fa fa-arrow-circle-right"></i>
				</a>
			</div>
		</div>
	</div>
	<div class='row'>
		<div class="col-md-3 col-sm-3 col-md-offset-11">
			<a href="{% url 'tour:fin-man-list' employee_account.id %}">View All</a>
	</div>


</div>
</div>
{% endblock %}

webapp/templates/tours/manager_dashboard.html
{% extends "base.html" %}
{% load staticfiles %}

{% block title %}Travel Portal | Manager{% endblock %}
{% block user %}{{ user }}{% endblock %}
{% block sidebar %}
    <li class='active'>
        <a href="{% url "tour:route" %}"><i class="fa fa-fw fa-dashboard"></i> Dashboard</a>
    </li>
    <li>
        <a href="{% url "tour:man-list" tour_id %}"><i class="fa fa-fw fa-plane"></i> Tours</a>
    </li>
{% endblock %}

{% block content %}
<div id="page-wrapper">
<div class='container-fluid'>
    <div class="row">
    <div class="col-lg-12">
        <h1>Dashboard <small>Manager</small></h1>
        <hr>
        <ol class="breadcrumb">
                <li class="active">
					<i class="fa fa-dashboard"></i> Dashboard
                </li>
        </ol>
    </div>
    </div>
    <div class="row">
        <div class="col-md-4 col-md-offset-4">
            <div class="list-group">          
                <a href="{% url 'tour:man-list-status' account_id 'approved' %}" class="list-group-item manager-approve">
                    <h3 class="pull-right">
                        <i class="fa fa-arrow-circle-right fa-2x fa-pos-icon"></i>
                    </h3>
                    <h4 class="list-group-item-heading count">
                        {{ for_submission_count }}</h4>
                    <p class="list-group-item-text">
                    Approved Tours <small>(For submission)</small></p>
                </a>
                <a href="{% url 'tour:man-list-status' account_id 'pending' %}" class="list-group-item manager-pending-approve">
                    <h3 class="pull-right">
                        <i class="fa fa-clock-o fa-2x fa-pos-icon"></i>
                    </h3>
                    <h4 class="list-group-item-heading count">
                        {{ pending_count }}</h4>
                    <p class="list-group-item-text">
                    Pending Tours <small>(For approval)</small></p>
                </a>
                <a href="{% url 'tour:man-list' employee_account.id %}" class="list-group-item manager-list">
                    <h3 class="pull-right">
                        <i class="fa fa-address-book fa-2x fa-pos-icon"></i>
                    </h3>
                    <h4 class="list-group-item-heading count">
                        {{ tours.count }}</h4>
                    <p class="list-group-item-text">
                    View All <small>(Employee Tour Status)</small></p>
                </a>
            </div>
        </div>
    </div>

</div>
</div>
{% endblock %}